name: Update material.json in dev branch

on:
  workflow_dispatch: null
  schedule:
    # UTC
    - cron: "0 20 * * *"

jobs:
  material_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Install node modules
        run: npm install
      - name: Update material.json
        run: npm run tool-material
      - name: Config git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Commit and push
        run: |
          if [[ -n $(git status --porcelain) ]]
          then
            git add .
            git commit -m 'Update material.json'
            git push
          else
            echo "Nothing to commit."
          fi
